// <auto-generated />
namespace TeeScoreService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class GameOwner_EntityDateCreated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GameOwner_EntityDateCreated));
        
        string IMigrationMetadata.Id
        {
            get { return "201812080859415_GameOwner_EntityDateCreated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
